/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Nyilonelycompany (https://sketchfab.com/Nyilonelycompany)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/munchkin-cat-58873374a64d482ca1ad7130c2f7e586
Title: Munchkin Cat
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Cat(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/import-models/cat/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.351}>
          <group name="Cat_Muchkin2abccleanermaterialmergergles">
            <group name="Object_2" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_3">
                <group
                  name="Object_4"
                  // position={[-0.004, 0.008, -0.001]}
                  // rotation={[1.055, -0.333, 0.436]}
                  scale={3.674}>
                  <group name="MorphMainGroup">
                    <mesh
                      name="Muchkin1_001"
                      castShadow
                      receiveShadow
                      geometry={nodes.Muchkin1_001.geometry}
                      material={materials.Muchkin1_001}
                      morphTargetDictionary={nodes.Muchkin1_001.morphTargetDictionary}
                      morphTargetInfluences={nodes.Muchkin1_001.morphTargetInfluences}
                    />
                  </group>
                </group>
                <group
                  name="Object_7"
                  // position={[-0.006, 0.003, -0.009]}
                  // rotation={[1.055, -0.333, 0.436]}
                  scale={3.674}>
                  <group name="MorphMainGroup_1">
                    <mesh
                      name="Muchkin1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Muchkin1.geometry}
                      material={materials.Muchkin1}
                      morphTargetDictionary={nodes.Muchkin1.morphTargetDictionary}
                      morphTargetInfluences={nodes.Muchkin1.morphTargetInfluences}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/import-models/cat/scene.gltf')
