/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jellystuff (https://sketchfab.com/jellystuff)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/stylized-vintage-coffee-machine-f04cee3f96c24f1ea30ddbff32ce7aa5
Title: Stylized Vintage Coffee Machine
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'
const CoffeeMachine = (props) => {
  const { nodes, materials } = useGLTF('/models/stylized_vintage_coffee_machine.glb')
  return (
    <Float floatIntensity={5}>
      <group {...props} dispose={null} scale={0.05}>
        <mesh
          castShadowF
          receiveShadow
          geometry={nodes.CoffeeMachine001_CoffeeMachine_0.geometry}
          material={materials.CoffeeMachine}
          position={[2.496, -0.272, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Coffee_cup001_CoffeeMachine_0.geometry}
          material={materials.CoffeeMachine}
          position={[-8.56, 27.873, -15.466]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Coffee_cup002_CoffeeMachine_0.geometry}
          material={materials.CoffeeMachine}
          position={[-3.08, 27.873, -15.348]}
          rotation={[0, 0.886, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Coffee_cup003_CoffeeMachine_0.geometry}
          material={materials.CoffeeMachine}
          position={[-8.072, 27.873, -9.879]}
          rotation={[-Math.PI, 1.517, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Coffee_cup004_CoffeeMachine_0.geometry}
          material={materials.CoffeeMachine}
          position={[-2.464, 27.873, -10.265]}
          rotation={[0, -0.434, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Coffee_cup005_CoffeeMachine_0.geometry}
          material={materials.CoffeeMachine}
          position={[-5.662, 29.762, -6.498]}
          rotation={[-3.063, 0.822, -1.721]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Coffee_cup006_CoffeeMachine_0.geometry}
          material={materials.CoffeeMachine}
          position={[-8.971, 27.873, -3.151]}
          rotation={[0, 0.678, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Coffee_cup007_CoffeeMachine_0.geometry}
          material={materials.CoffeeMachine}
          position={[13.461, 11.007, 9.078]}
          rotation={[0, 0.678, 0]}
        />
      </group>
    </Float>
  )
}

useGLTF.preload('/models/stylized_vintage_coffee_machine.glb')

export default CoffeeMachine