/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Zhuier (https://sketchfab.com/Zhuier)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/oiiaioooooiai-cat-30d27bf7fb224849b76e208a6eccdb36
Title: Oiiaioooooiai Cat
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const SmallCat = (props) => {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/SmallCat.glb')

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="191d233c94184f188ac4fad4b07dc182fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Muchkin1002">
                  <mesh
                    name="0"
                    castShadow
                    receiveShadow
                    geometry={nodes['0'].geometry}
                    material={materials.Muchkin2}
                    morphTargetDictionary={nodes['0'].morphTargetDictionary}
                    morphTargetInfluences={nodes['0'].morphTargetInfluences}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/SmallCat.glb')

export default SmallCat
